/** @vitest-environment jsdom */
import { ThemeProvider } from '@mui/material'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createMemoryRouter } from 'react-router'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { createAppTheme } from '@/theme'
import AppRouter from '@/router/AppRouter'
import { useAuthStore } from '@/stores/auth'
import { destinationBudget, destinationNode, destinationPolicies, destinationStatus, samplePolicy } from '@/test/accessControlFixtures'
import type { DestinationListDetail, DestinationListSummary } from '@/api/accessControl'
const api = vi.hoisted(() => ({ get: vi.fn(), put: vi.fn(), post: vi.fn(), delete: vi.fn() }))
vi.mock('@/api/client', () => ({ client: api }))
const confirmation = vi.hoisted(() => vi.fn())
vi.mock('@/components/ConfirmHost', () => ({ confirm: confirmation }))
const snack = vi.hoisted(() => vi.fn())
vi.mock('@/components/SnackbarHost', () => ({ pushSnack: snack }))
vi.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string, options?: Record<string, unknown>) => key + (options?.name ? ` ${options.name}` : options?.template ? ` ${options.template}` : key === 'admin:access_control.templates.count' ? ` ${options?.count}/${options?.regexps}` : ''), i18n: { language: 'en-US' } }) }))
vi.mock('@/components/CodeEditor', () => ({ default: (p: { value: string; onChange: (s: string) => void; ariaLabel: string; readOnly: boolean }) => <textarea aria-label={p.ariaLabel} value={p.value} readOnly={p.readOnly} onChange={e => p.onChange(e.target.value)} /> }))
import AccessControlView from './AccessControlView'
const P = 'admin:access_control.'
it('keeps the list editor title heading separate from its close action', async () => {
  listsAPI([]); mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}lists.create` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}list_editor.create_title` })
  const heading = within(dialog).getByRole('heading', { name: `${P}list_editor.create_title` })
  expect(within(heading).queryByRole('button')).toBeNull()
  expect(within(dialog).getByRole('button', { name: 'common:actions.close' })).toBeTruthy()
  expect(document.querySelectorAll('#access-list-editor-title')).toHaveLength(1)
})
it('keeps a saved list drawer heading separate from its close action', async () => {
  listsAPI([listSummary]); mount('/admin/access-control?tab=lists&sheet=list&list=7')
  const dialog = await screen.findByRole('dialog', { name: 'Finance' })
  const heading = within(dialog).getByRole('heading', { name: /^Finance$/ })
  expect(within(heading).queryByRole('button')).toBeNull()
  expect(within(dialog).getByRole('button', { name: 'common:actions.close' })).toBeTruthy()
  expect(document.querySelectorAll('#access-list-entries-title')).toHaveLength(1)
})
it('downloads an unavailable catalog manually from lists without duplicate writes or losing filters', async () => {
  listsAPI([{ ...listSummary, state: 'failed', last_fetched_at: null }])
  const original = api.get.getMockImplementation()!
  let downloaded = false, finish!: (value: unknown) => void
  api.get.mockImplementation(async (url: string, config?: unknown) => {
    if (url.endsWith('/categories')) { if (!downloaded) throw err(503, 'dest_geosite_unavailable'); return { data: { categories: [], updated_at: 4000 } } }
    return original(url, config)
  })
  api.post.mockImplementation(() => new Promise(resolve => { finish = resolve }))
  const router = mount('/admin/access-control?tab=lists&lst_state=problem')
  await screen.findByText(`${P}categories.missing`)
  const download = screen.getByRole('button', { name: `${P}categories.download` })
  expect(api.post).not.toHaveBeenCalled()
  fireEvent.click(download); fireEvent.click(download)
  await waitFor(() => expect(api.post).toHaveBeenCalledTimes(1))
  expect(api.post).toHaveBeenCalledWith('/admin/dest/geosite/refresh', undefined, { _skipErrorToast: true })
  expect(download.getAttribute('aria-busy')).toBe('true')
  downloaded = true; finish({ data: {} })
  await waitFor(() => expect(screen.queryByText(`${P}categories.missing`)).toBeNull())
  expect(router.state.location.search).toBe('?tab=lists&lst_state=problem')
})
it('keeps the download busy after HTTP 202 until the backend task settles', async () => {
  listsAPI([listSummary]); const original = api.get.getMockImplementation()!
  let queued = false
  api.get.mockImplementation(async (url: string, config?: unknown) => {
    if (url.endsWith('/categories')) throw Object.assign(err(503, 'dest_geosite_unavailable'), { response: { status: 503, data: { error: 'dest_geosite_unavailable', refreshing: queued, last_error: '' } } })
    return original(url, config)
  })
  api.post.mockImplementation(async () => { queued = true; return { data: {} } })
  mount('/admin/access-control?tab=lists')
  const button = await screen.findByRole('button', { name: `${P}categories.download` })
  fireEvent.click(button)
  await waitFor(() => expect(api.get.mock.calls.filter(([url]) => url.endsWith('/categories')).length).toBeGreaterThan(1))
  expect(button.getAttribute('aria-busy')).toBe('true')
  expect((button as HTMLButtonElement).disabled).toBe(true)
  expect(api.post).toHaveBeenCalledTimes(1)
  expect(screen.getAllByRole('button', { name: 'Finance' }).length).toBeGreaterThan(0)
})
it('shows a failed background download after its accepted HTTP request', async () => {
  listsAPI([listSummary]); const original = api.get.getMockImplementation()!
  let failed = false
  api.get.mockImplementation(async (url: string, config?: unknown) => {
    if (url.endsWith('/categories')) throw Object.assign(err(503, 'dest_geosite_unavailable'), { response: { status: 503, data: { error: 'dest_geosite_unavailable', refreshing: false, last_error: failed ? 'download_failed' : '' } } })
    return original(url, config)
  })
  api.post.mockImplementation(async () => { failed = true; return { data: {} } })
  mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}categories.download` }))
  await screen.findByText(`${P}categories.failed`)
  await waitFor(() => expect(screen.getByRole('button', { name: `${P}categories.download` }).getAttribute('aria-busy')).toBeNull())
  expect(api.post).toHaveBeenCalledTimes(1)
})
it('keeps list rows and the manual catalog retry after a failed download', async () => {
  listsAPI([listSummary]); const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => { if (url.endsWith('/categories')) throw err(503, 'dest_geosite_unavailable'); return original(url, config) })
  api.post.mockRejectedValue(err(502, 'download_failed'))
  mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}categories.download` }))
  await screen.findByText(`${P}categories.failed`)
  expect(screen.getAllByRole('button', { name: 'Finance' }).length).toBeGreaterThan(0)
  await waitFor(() => expect(screen.getByRole('button', { name: `${P}categories.download` }).getAttribute('aria-busy')).toBeNull())
  expect(api.post).toHaveBeenCalledTimes(1)
})
it('uses the same manual catalog download in a list editor and preserves its draft', async () => {
  listsAPI([]); const original = api.get.getMockImplementation()!
  let downloaded = false, finish!: (value: unknown) => void
  api.get.mockImplementation(async (url: string, config?: unknown) => {
    if (url.endsWith('/categories')) { if (!downloaded) throw err(503, 'dest_geosite_unavailable'); return { data: { categories: [], updated_at: 4000 } } }
    return original(url, config)
  })
  api.post.mockImplementation(() => new Promise(resolve => { finish = resolve }))
  mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}lists.create` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}list_editor.create_title` })
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}lists.geosite` }))
  await within(dialog).findByText(`${P}categories.missing`)
  const name = within(dialog).getByRole('textbox', { name: `${P}list_editor.name` }) as HTMLInputElement
  fireEvent.change(name, { target: { value: 'Financial draft' } })
  expect(api.post).not.toHaveBeenCalled()
  const download = within(dialog).getByRole('button', { name: `${P}categories.download` })
  fireEvent.click(download); fireEvent.click(download)
  await waitFor(() => expect(api.post).toHaveBeenCalledTimes(1))
  downloaded = true; finish({ data: {} })
  await within(dialog).findByRole('combobox', { name: `${P}categories.category` })
  expect(name.value).toBe('Financial draft')
  expect(api.post).toHaveBeenCalledWith('/admin/dest/geosite/refresh', undefined, { _skipErrorToast: true })
})
it('keeps the template origin in a new policy title when its draft name changes', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.create` }))
  fireEvent.click(screen.getByRole('menuitem', { name: new RegExp(`${P}policies.template_mail`) }))
  const title = `${P}editor.template_title ${P}policies.template_mail`
  const dialog = await screen.findByRole('dialog', { name: title })
  fireEvent.change(within(dialog).getByRole('textbox', { name: `${P}editor.name` }), { target: { value: 'My mail policy' } })
  expect(within(dialog).getByRole('heading', { name: title })).toBeTruthy()
  expect(api.post.mock.calls.some(([url]) => url === '/admin/dest/policies')).toBe(false)
})
it('explains allowlist bypass on demand and hides the risk control when allowing', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog')
  expect(within(dialog).getByRole('switch', { name: `${P}editor.counts_as_risk` })).toBeTruthy()
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}editor.action_allow` }))
  expect(within(dialog).queryByRole('switch', { name: `${P}editor.counts_as_risk` })).toBeNull()
  expect(screen.queryByText(`${P}editor.allow_detail`)).toBeNull()
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}editor.allow_summary` }))
  await screen.findByText(`${P}editor.allow_detail`)
  expect(api.put).not.toHaveBeenCalled()
})
it('offers expandable IP and BT matching limits without losing inline conditions', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog')
  expect(within(dialog).getByRole('button', { name: `${P}editor.cidrs_summary` })).toBeTruthy()
  expect(within(dialog).getByRole('button', { name: `${P}editor.bt_summary` })).toBeTruthy()
  const ports = within(dialog).getByRole('textbox', { name: `${P}editor.ports` }) as HTMLInputElement
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}editor.cidrs_summary` }))
  await screen.findByText(`${P}editor.cidrs_detail`)
  expect(ports.value).toBe('25,465,587')
  expect(api.put).not.toHaveBeenCalled()
})
it('marks unavailable list choices and explains their pending contribution without a write', async () => {
  listsAPI([{ ...listSummary, state: 'pending', entry_count: 0 }, { ...listSummary, id: 8, name: 'Empty custom', kind: 'custom', entry_count: 0 }, { ...listSummary, id: 9, name: 'Owned', owner_group_id: 3 }])
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog')
  fireEvent.mouseDown(within(dialog).getByRole('combobox', { name: `${P}editor.lists` }))
  const option = await screen.findByRole('option', { name: new RegExp('Finance') })
  expect(within(option).getByText(`${P}editor.list_attention`)).toBeTruthy()
  const empty = screen.getByRole('option', { name: new RegExp('Empty custom') })
  expect(empty.getAttribute('aria-disabled')).toBe('true')
  expect(empty.getAttribute('title')).toBe(`${P}editor.list_empty`)
  expect(screen.queryByRole('option', { name: new RegExp('Owned') })).toBeNull()
  fireEvent.click(empty)
  expect(within(dialog).queryByRole('button', { name: `${P}editor.list_pending_summary` })).toBeNull()
  fireEvent.click(option)
  await waitFor(() => expect(api.post.mock.calls.some(([url, body]) => url.endsWith('/policies/preview') && JSON.stringify(body.list_ids) === '[7]')).toBe(true))
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}editor.list_pending_summary` }))
  await screen.findByText(`${P}editor.list_pending_detail`)
  expect(api.put).not.toHaveBeenCalled()
})
it('keeps one guarded save button in the phone editor header while its summary stays below', async () => {
  vi.stubGlobal('matchMedia', vi.fn((query: string) => ({ matches: query.includes('max-width'), media: query, onchange: null, addListener: vi.fn(), removeListener: vi.fn(), addEventListener: vi.fn(), removeEventListener: vi.fn(), dispatchEvent: vi.fn() })))
  let finish!: (value: unknown) => void
  api.put.mockImplementation(() => new Promise(resolve => { finish = resolve }))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  const heading = within(dialog).getByRole('heading', { name: `${P}editor.edit_title No mail` })
  const save = within(heading.parentElement!).getByRole('button', { name: 'common:actions.save' })
  expect(within(dialog).getAllByRole('button', { name: 'common:actions.save' })).toHaveLength(1)
  expect((save as HTMLButtonElement).disabled).toBe(true)
  fireEvent.change(within(dialog).getByRole('textbox', { name: `${P}editor.name` }), { target: { value: 'Phone draft' } })
  fireEvent.click(save); fireEvent.click(save)
  await waitFor(() => expect(api.put).toHaveBeenCalledTimes(1))
  expect((save as HTMLButtonElement).disabled).toBe(true)
  expect(save.getAttribute('aria-busy')).toBe('true')
  expect(within(dialog).getByText(`${P}editor.metadata_hint`)).toBeTruthy()
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.close' }))
  expect(screen.getByRole('dialog')).toBe(dialog)
  finish({ data: samplePolicy }); await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
})
it('selects UDP and the unrestricted network explicitly without changing destination conditions', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  const network = within(dialog).getByRole('group', { name: `${P}editor.network` })
  fireEvent.click(within(network).getByRole('button', { name: 'UDP' }))
  expect(within(network).getByRole('button', { name: 'UDP' }).getAttribute('aria-pressed')).toBe('true')
  fireEvent.click(within(network).getByRole('button', { name: `${P}editor.any` }))
  expect(within(network).getByRole('button', { name: `${P}editor.any` }).getAttribute('aria-pressed')).toBe('true')
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(api.put).toHaveBeenCalledWith('/admin/dest/policies/12', expect.objectContaining({ inline: expect.objectContaining({ ports: '25,465,587', network: '' }), updated_at: 2000 }), { _skipErrorToast: true }))
})
it('supports arrow-key selection and focus in action and network segments', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  const action = within(dialog).getByRole('group', { name: `${P}editor.action` })
  const block = within(action).getByRole('button', { name: `${P}editor.action_block` })
  block.focus(); fireEvent.keyDown(block, { key: 'ArrowRight' })
  const observation = within(action).getByRole('button', { name: `${P}editor.action_observe` })
  expect(observation.getAttribute('aria-pressed')).toBe('true'); expect(document.activeElement).toBe(observation)
  const network = within(dialog).getByRole('group', { name: `${P}editor.network` })
  const tcp = within(network).getByRole('button', { name: 'TCP' })
  tcp.focus(); fireEvent.keyDown(tcp, { key: 'ArrowRight' })
  const udp = within(network).getByRole('button', { name: 'UDP' })
  expect(udp.getAttribute('aria-pressed')).toBe('true'); expect(document.activeElement).toBe(udp)
  fireEvent.keyDown(udp, { key: 'ArrowRight' })
  const any = within(network).getByRole('button', { name: `${P}editor.any` })
  expect(any.getAttribute('aria-pressed')).toBe('true'); expect(document.activeElement).toBe(any)
  expect(api.put).not.toHaveBeenCalled()
})
it('starts blank additional conditions collapsed and preserves values through collapse', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.create` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}templates.blank` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}editor.create_title` })
  const toggle = within(dialog).getByRole('button', { name: `${P}editor.more_conditions` })
  expect(toggle.getAttribute('aria-expanded')).toBe('false')
  expect(within(dialog).queryByRole('textbox', { name: `${P}editor.ports` })).toBeNull()
  fireEvent.click(toggle)
  const ports = await within(dialog).findByRole('textbox', { name: `${P}editor.ports` })
  fireEvent.change(ports, { target: { value: '443' } })
  fireEvent.click(within(dialog).getByRole('checkbox', { name: `${P}editor.bt` }))
  fireEvent.click(toggle)
  await waitFor(() => expect(toggle.getAttribute('aria-expanded')).toBe('false'))
  expect(toggle.textContent).toContain(`${P}editor.ports_value`)
  expect(toggle.textContent).toContain(`${P}editor.bt`)
  fireEvent.click(toggle)
  expect((await within(dialog).findByRole('textbox', { name: `${P}editor.ports` }) as HTMLInputElement).value).toBe('443')
  expect((within(dialog).getByRole('checkbox', { name: `${P}editor.bt` }) as HTMLInputElement).checked).toBe(true)
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.cancel' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(api.post.mock.calls.some(([url]) => url === '/admin/dest/policies')).toBe(false)
})
it('opens existing inline conditions initially and reveals a collapsed server field error', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  const toggle = within(dialog).getByRole('button', { name: `${P}editor.more_conditions` })
  expect(toggle.getAttribute('aria-expanded')).toBe('true')
  expect((within(dialog).getByRole('textbox', { name: `${P}editor.ports` }) as HTMLInputElement).value).toBe('25,465,587')
  fireEvent.click(toggle)
  fireEvent.change(within(dialog).getByRole('textbox', { name: `${P}editor.name` }), { target: { value: 'Draft name' } })
  api.put.mockRejectedValueOnce({ isAxiosError: true, response: { status: 400, data: { error: 'ports_invalid', field: 'ports' } } })
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(toggle.getAttribute('aria-expanded')).toBe('true'))
  const ports = await within(dialog).findByRole('textbox', { name: `${P}editor.ports` })
  expect(ports.getAttribute('aria-invalid')).toBe('true')
  expect((within(dialog).getByRole('textbox', { name: `${P}editor.name` }) as HTMLInputElement).value).toBe('Draft name')
  expect(api.put).toHaveBeenCalledTimes(1)
  fireEvent.click(toggle)
  api.put.mockRejectedValueOnce({ isAxiosError: true, response: { status: 400, data: { error: 'ports_invalid', field: 'ports' } } })
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(api.put).toHaveBeenCalledTimes(2))
  await waitFor(() => expect(toggle.getAttribute('aria-expanded')).toBe('true'))
})
it('opens settings from the page menu without publishing or losing list filters', async () => {
  settingsAPI(); const router = mount('/admin/access-control?tab=lists&lst_state=problem')
  fireEvent.click(await screen.findByRole('button', { name: `${P}more` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}settings.title` }))
  await screen.findByRole('dialog', { name: `${P}settings.title` })
  expect(router.state.location.search).toBe('?tab=lists&lst_state=problem&sheet=settings')
  expect(screen.queryByRole('menu')).toBeNull()
  expect(api.post).not.toHaveBeenCalled(); expect(api.put).not.toHaveBeenCalled()
})
it('requires confirmation before the menu pauses execution and preserves cancellation', async () => {
  confirmation.mockResolvedValue(false); mount()
  await screen.findByRole('status')
  fireEvent.click(screen.getByRole('button', { name: `${P}more` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}pause` }))
  await waitFor(() => expect(confirmation).toHaveBeenCalledWith(expect.objectContaining({ title: `${P}confirm.pause_title`, destructive: true })))
  expect(api.put).not.toHaveBeenCalled(); expect(api.post).not.toHaveBeenCalled()
  expect(screen.queryByRole('menu')).toBeNull()
})
it('disables menu pause when the first status read failed', async () => {
  const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => { if (url.endsWith('/status')) throw err(500, 'unavailable'); return original(url, config) })
  mount(); await screen.findByRole('alert')
  fireEvent.click(screen.getByRole('button', { name: `${P}more` }))
  const pause = screen.getByRole('menuitem', { name: `${P}pause` })
  expect(pause.getAttribute('aria-disabled')).toBe('true')
  fireEvent.click(pause)
  expect(confirmation).not.toHaveBeenCalled(); expect(api.put).not.toHaveBeenCalled()
})
it('offers resume rather than pause after a confirmed paused status', async () => {
  const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => url.endsWith('/status') ? { data: destinationStatus({ paused: true }) } : original(url, config))
  mount(); await screen.findByRole('status')
  fireEvent.click(screen.getByRole('button', { name: `${P}more` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}resume` }))
  await waitFor(() => expect(api.put).toHaveBeenCalledWith('/admin/dest/pause', { paused: false }, { _skipErrorToast: true }))
  expect(confirmation).toHaveBeenCalledWith(expect.objectContaining({ title: `${P}confirm.resume_title`, destructive: false }))
  expect(api.post).not.toHaveBeenCalled()
})
it('explains only the selected tab and preserves its filters without writing', async () => {
  const router = mount('/admin/access-control?lst_state=problem')
  fireEvent.click(await screen.findByRole('button', { name: `${P}help.label ${P}policies.title` }))
  expect(screen.getByText(`${P}help.policies`)).toBeTruthy()
  fireEvent.keyDown(screen.getByText(`${P}help.policies`), { key: 'Escape' })
  await waitFor(() => expect(screen.queryByText(`${P}help.policies`)).toBeNull())
  fireEvent.click(screen.getByRole('tab', { name: `${P}lists.title` }))
  fireEvent.click(screen.getByRole('button', { name: `${P}help.label ${P}lists.title` }))
  expect(screen.getByText(`${P}help.lists`)).toBeTruthy()
  expect(screen.queryByText(`${P}help.policies`)).toBeNull()
  expect(router.state.location.search).toBe('?lst_state=problem&tab=lists')
  expect(api.post).not.toHaveBeenCalled(); expect(api.put).not.toHaveBeenCalled()
})
it('keeps policies usable after a first status failure and retries only the status read', async () => {
  const original = api.get.getMockImplementation()!; let statusReads = 0
  api.get.mockImplementation(async (url: string, config?: unknown) => { if (url.endsWith('/status') && ++statusReads === 1) throw err(500, 'unavailable'); return original(url, config) })
  mount()
  expect((await screen.findByRole('alert')).textContent).toContain(`${P}status_failed`)
  expect(screen.getByRole('button', { name: `${P}policies.edit No mail` })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.retry' }))
  await waitFor(() => expect(screen.getByRole('status').textContent).toBe(`${P}verdict.applied`))
  expect(statusReads).toBe(2)
  expect(api.post).not.toHaveBeenCalled()
})
it.each([500, 503])('keeps the last status verdict when an invalidated refresh fails with %s', async code => {
  const original = api.get.getMockImplementation()!; let failStatus = false
  api.get.mockImplementation(async (url: string, config?: unknown) => { if (url.endsWith('/status') && failStatus) throw err(code, 'unavailable'); return original(url, config) })
  mount(); const live = await screen.findByRole('status')
  await waitFor(() => expect(live.textContent).toBe(`${P}verdict.applied`))
  failStatus = true; fireEvent.click(screen.getByRole('button', { name: `${P}publish` }))
  await screen.findByText(`${P}status_stale`)
  expect(live.textContent).toBe(`${P}verdict.applied`)
  expect(live.textContent).not.toContain('read_at')
  expect(screen.getByRole('button', { name: `${P}policies.edit No mail` })).toBeTruthy()
})
it('opens upgrade coverage atomically from its summary and closes back to the list tab', async () => {
  const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => url.endsWith('/status') ? { data: destinationStatus({ nodes: [destinationNode(), destinationNode({ panel_id: 2, panel_name: 'Old node', state: 'unsupported_version', supports: { policy: false, hits: false, usage: false } }), destinationNode({ panel_id: 3, panel_name: 'Offline node', state: 'offline' })] }) } : original(url, config))
  const router = mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}not_executing.upgrade` }))
  const drawer = await screen.findByRole('dialog', { name: `${P}coverage.title` })
  expect(router.state.location.search).toBe('?tab=lists&sheet=nodes&node_state=upgrade')
  expect(within(drawer).getByText('Old node')).toBeTruthy()
  expect(within(drawer).queryByText('Offline node')).toBeNull()
  fireEvent.click(within(drawer).getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
})
it('opens the full list view for a publication quota error without carrying a problem filter', async () => {
  const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => url.endsWith('/status') ? { data: destinationStatus({ publish_error: { kind: 'domains', used: 51000, limit: 50000 } }) } : original(url, config))
  const router = mount('/admin/access-control?lst_state=problem')
  fireEvent.click(await screen.findByRole('button', { name: `${P}open_lists` }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
  expect(screen.getByRole('tab', { name: `${P}lists.title`, selected: true })).toBeTruthy()
  expect(api.post).not.toHaveBeenCalled()
})
it('admits a node retry only once while its request is pending', async () => {
  const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => url.endsWith('/status') ? { data: destinationStatus({ nodes: [destinationNode({ state: 'rejected' })] }) } : original(url, config))
  let finish!: (value: unknown) => void
  api.post.mockImplementation(() => new Promise(resolve => { finish = resolve }))
  mount('/admin/access-control?sheet=nodes')
  const retry = await screen.findByRole('button', { name: `${P}coverage.retry` })
  fireEvent.click(retry); fireEvent.click(retry)
  await waitFor(() => expect(api.post).toHaveBeenCalledTimes(1))
  expect(retry.getAttribute('aria-busy')).toBe('true')
  finish({ data: { retry_requested: true } })
  await waitFor(() => expect(snack).toHaveBeenCalledWith(`${P}coverage.retry_requested`, 'success'))
})
it('opens the account Access drawer from the header and closes back to the page', async () => {
  const original = api.get.getMockImplementation()!
  api.get.mockImplementation(async (url: string, config?: unknown) => {
    if (url === '/admin/users') return { data: { items: [{ id: 13, upn: 'alice@example.test' }], total: 1 } }
    if (url === '/admin/users/13') return { data: { id: 13, upn: 'alice@example.test' } }
    if (url === '/admin/dest/users/13') return { data: { group: null, exemption: null } }
    if (url === '/admin/risk-center/users/13') return { data: { user: { id: 13, upn: 'alice@example.test', display_name: '', role: 'user', enabled: true, group_id: 0, group_name: '', traffic_limit_bytes: 0 }, attention: [], review: { dismissed: false, trusted: false, escalated: [] }, geo: null, signals: [], live: {}, devices: [], device_window_hours: 24, devices_unavailable: false } }
    if (url.startsWith('/admin/risk-center/')) throw err(503, 'unavailable')
    return original(url, config)
  })
  const router = mount()
  fireEvent.mouseDown(await screen.findByRole('combobox', { name: `${P}view_account` }))
  fireEvent.click(await screen.findByRole('option', { name: 'alice@example.test' }))
  await screen.findByRole('tab', { name: 'admin:risk_center.drawer.tab_access', selected: true })
  expect(router.state.location.search).toBe('?user=13')
  fireEvent.click(screen.getByRole('button', { name: 'admin:risk_center.drawer.close' }))
  await waitFor(() => expect(router.state.location.search).toBe(''))
})
it('opens list refresh settings focused on the refresh interval', async () => {
  listsAPI([listSummary]); settingsAPI(); mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}list_editor.change_refresh` }))
  const refresh = await screen.findByRole('textbox', { name: `${P}settings.dest_list_refresh_hours` })
  await waitFor(() => expect(document.activeElement).toBe(refresh))
})
it('replaces a cold list sheet with refresh settings and closes in place', async () => {
  listsAPI([listSummary]); settingsAPI(); const router = mount('/admin/access-control?tab=lists&sheet=list&list=7')
  fireEvent.click(await screen.findByRole('button', { name: 'common:actions.edit' }))
  const editor = await screen.findByRole('dialog', { name: `${P}list_editor.edit_title` })
  fireEvent.click(within(editor).getByRole('button', { name: `${P}list_editor.change_refresh` }))
  const settings = await screen.findByRole('dialog', { name: `${P}settings.title` })
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists&sheet=settings'))
  fireEvent.click(within(settings).getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
})
it('replaces a cold list drawer with a state-prefilled test and closes in place', async () => {
  listsAPI([listSummary]); const router = mount('/admin/access-control?tab=lists&sheet=list&list=7')
  fireEvent.click(await screen.findByRole('button', { name: `${P}test.test_entry domain:bank.example` }))
  const target = await screen.findByRole('textbox', { name: `${P}test.target` }) as HTMLInputElement
  expect(target.value).toBe('bank.example'); expect(router.state.location.search).toBe('?tab=lists&sheet=test')
  expect(router.state.location.state).toEqual({ prefill: { target: 'bank.example' } })
  expect(api.post).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
  expect(router.state.location.state).toBeNull()
})
it('opens testing from the page without automatically posting any target', async () => {
  const router = mount()
  fireEvent.click(await screen.findByRole('button', { name: `${P}test.title` }))
  await screen.findByRole('dialog', { name: `${P}test.title` })
  expect(router.state.location.search).toBe('?sheet=test')
  expect(api.post).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe(''))
})
it('opens the matched policy and replaces the sheet history without leaking the target', async () => {
  api.post.mockResolvedValue({ data: { verdict: 'block', terminating_step: 'block', unpublished: false, steps: [{ step: 'block', result: 'hit', policy_id: 12, name: 'No mail' }], notes: [], nodes: [] } })
  const router = mount('/admin/access-control?tab=lists&sheet=test')
  fireEvent.change(await screen.findByRole('textbox', { name: `${P}test.target` }), { target: { value: 'secret.example.test' } })
  fireEvent.click(screen.getByRole('button', { name: `${P}test.submit` }))
  fireEvent.click(await screen.findByRole('button', { name: `${P}test.open_policy No mail` }))
  await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  expect(router.state.location.search).toBe('?tab=policies')
  expect(screen.queryByRole('dialog', { name: `${P}test.title` })).toBeNull()
})
it('opens exemptions with owned history and preserves the list tab on cold close', async () => {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/exemptions') ? { items: [] } : url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus() : url.endsWith('/lists') ? { items: [] } : { effective: {} } }))
  const router = mount('/admin/access-control?tab=lists&sheet=exemptions')
  const drawer = await screen.findByRole('dialog', { name: `${P}exemptions.title` })
  expect(await within(drawer).findByText(`${P}exemptions.empty`)).toBeTruthy()
  fireEvent.click(within(drawer).getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
})
it('opens an exempt account in one navigation that clears sheet-owned parameters', async () => {
  api.get.mockImplementation(async (url: string) => {
    if (url.startsWith('/admin/risk-center/')) throw err(503, 'unavailable')
    return { data: url.endsWith('/exemptions') ? { items: [{ user_id: 13, upn: 'alice@test', reason: 'Diagnostics', created_by: 42, created_by_upn: 'admin@test', created_at: Date.now(), expires_at: null, expired: false }] } : url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus() : url.endsWith('/lists') ? { items: [] } : { effective: {} } }
  })
  const router = mount('/admin/access-control?tab=lists&sheet=exemptions&list=7&node_state=problem')
  fireEvent.click(await screen.findByRole('button', { name: `${P}exemptions.menu` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}exemptions.open_account` }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists&user=13'))
  expect(router.state.location.state).toBeNull()
  expect(screen.queryByRole('dialog', { name: `${P}exemptions.title` })).toBeNull()
})
it('replaces an owned exemptions sheet so closing the account returns to the page without reviving it', async () => {
  api.get.mockImplementation(async (url: string) => {
    if (url.startsWith('/admin/risk-center/')) throw err(503, 'unavailable')
    return { data: url.endsWith('/exemptions') ? { items: [{ user_id: 13, upn: 'alice@test', reason: 'Diagnostics', created_by: 42, created_by_upn: 'admin@test', created_at: Date.now(), expires_at: null, expired: false }] } : url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus() : url.endsWith('/lists') ? { items: [] } : { effective: {} } }
  })
  const router = mount()
  fireEvent.click(await screen.findByRole('button', { name: `${P}exemptions.manage` }))
  fireEvent.click(await screen.findByRole('button', { name: `${P}exemptions.menu` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}exemptions.open_account` }))
  fireEvent.click(await screen.findByRole('button', { name: 'admin:risk_center.drawer.close' }))
  await waitFor(() => expect(router.state.location.search).toBe(''))
  expect(screen.queryByRole('dialog', { name: `${P}exemptions.title` })).toBeNull()
})
it('opens only the account on conflicting cold drawer parameters and clears the inactive sheet on close', async () => {
  api.get.mockImplementation(async (url: string) => {
    if (url.startsWith('/admin/risk-center/')) throw err(503, 'unavailable')
    return { data: url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus() : url.endsWith('/lists') ? { items: [] } : { effective: {} } }
  })
  const router = mount('/admin/access-control?tab=lists&user=13&sheet=exemptions&list=7&node_state=problem')
  const close = await screen.findByRole('button', { name: 'admin:risk_center.drawer.close' })
  expect(screen.queryByRole('dialog', { name: `${P}exemptions.title` })).toBeNull()
  expect(api.get.mock.calls.some(([url]) => url.endsWith('/exemptions'))).toBe(false)
  fireEvent.click(close)
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
})
const err = (status: number, error: string) => ({ isAxiosError: true, response: { status, data: { error } }, message: error })
function mount(initial = '/admin/access-control') {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })
  const router = createMemoryRouter([{ path: '/admin/access-control', element: <AccessControlView /> }, { path: '/admin/dashboard', element: <p>Dashboard</p> }], { initialEntries: [initial] })
  render(<ThemeProvider theme={createAppTheme({ mode: 'light', sourceColor: '#6750a4', language: 'en-US' })}><QueryClientProvider client={client}><AppRouter router={router} /></QueryClientProvider></ThemeProvider>)
  return router
}
beforeEach(() => {
  vi.clearAllMocks()
  useAuthStore.setState({ userId: 42, role: 'admin', authEpoch: 5 })
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ published_has_access_control: true }) : url.endsWith('/status') ? destinationStatus() : url.endsWith('/categories') ? { categories: [], updated_at: 1000 } : url.endsWith('/lists') ? { items: [] } : url.endsWith('/groups') ? { items: [], total: 0 } : { settings: {}, defaults: {}, effective: { dest_policy_apply_min_seconds: 75 } } }))
  api.put.mockResolvedValue({ data: samplePolicy })
  api.post.mockResolvedValue({ data: { budget: destinationPolicies().budget } })
  confirmation.mockResolvedValue(true)
})
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const listReport = { accepted: 1, ignored: 1, ignored_broad: 1, rewritten: 0, samples: [{ line: 1, text: 'domain:hsbc', reason: 'broad_entry' }] }
const listDetail: DestinationListDetail = { id: 7, name: 'Finance', kind: 'geosite', source_url: '', geosite_category: 'category-finance', geosite_attrs: '', owner_group_id: 0, updated_at: 3000, entry_count: 1, regexp_count: 0, state: 'ready', last_fetched_at: 1000, last_error: '', entries: ['domain:bank.example'], content_sha256: 'full-digest', parse_report: listReport }
const listSummary: DestinationListSummary = { ...listDetail, parse_report_summary: listReport, used_by: [] }
function listsAPI(items: DestinationListSummary[]) {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus() : url.endsWith('/categories') ? { categories: [], updated_at: 1000 } : url.endsWith('/lists') ? { items, budget: destinationBudget, refresh_hours: 12 } : url.endsWith('/lists/7') ? listDetail : { settings: {}, effective: {} } }))
}
function settingsAPI() {
  const original = api.get.getMockImplementation()!
  const defaults = { dest_hit_retention_days: 30, dest_trial_retention_days: 7, dest_usage_retention_days: 7, dest_list_refresh_hours: 24, dest_policy_apply_min_seconds: 60 }
  api.get.mockImplementation(async (url: string, config?: unknown) => url.endsWith('/dest/settings') ? { data: { settings: { ...defaults }, defaults, effective: defaults } } : original(url, config))
}
it('opens a list policy reference in the real editor and dismisses the usage popover', async () => {
  listsAPI([{ ...listSummary, used_by: [{ kind: 'policy', id: 12, name: 'No mail' }] }])
  const router = mount('/admin/access-control?tab=lists&lst_state=problem')
  // Show the healthy list after clearing the problem filter.
  fireEvent.click(await screen.findByRole('button', { name: `${P}lists.problem 0` }))
  fireEvent.click((await screen.findAllByRole('button', { name: `${P}lists.open_references Finance` }))[0])
  fireEvent.click(screen.getByRole('button', { name: `${P}lists.open_policy No mail` }))
  await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  expect(router.state.location.search).toBe('?tab=policies')
  expect(screen.queryByRole('dialog', { name: `${P}lists.references_title Finance` })).toBeNull()
  expect(api.post.mock.calls.every(([url]) => url.endsWith('/policies/preview'))).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.cancel' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  fireEvent.click(screen.getByRole('tab', { name: `${P}lists.title` }))
  fireEvent.click((await screen.findAllByRole('button', { name: `${P}lists.open_references Finance` }))[0])
  fireEvent.click(screen.getByRole('button', { name: `${P}lists.open_policy No mail` }))
  await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
})
it('warns when a list references a deleted policy instead of creating a draft editor', async () => {
  listsAPI([{ ...listSummary, used_by: [{ kind: 'policy', id: 999, name: 'Deleted policy' }] }])
  mount('/admin/access-control?tab=lists')
  fireEvent.click((await screen.findAllByRole('button', { name: `${P}lists.open_references Finance` }))[0])
  fireEvent.click(screen.getByRole('button', { name: `${P}lists.open_policy Deleted policy` }))
  await waitFor(() => expect(snack).toHaveBeenCalledWith(`${P}test.policy_missing`, 'warning'))
  expect(screen.queryByRole('dialog')).toBeNull()
})
it('does not reopen a consumed matched-policy request after switching tabs', async () => {
  api.post.mockResolvedValue({ data: { verdict: 'block', terminating_step: 'block', unpublished: false, steps: [{ step: 'block', result: 'hit', policy_id: 12, name: 'No mail' }], notes: [], nodes: [] } })
  mount('/admin/access-control?sheet=test')
  fireEvent.change(await screen.findByRole('textbox', { name: `${P}test.target` }), { target: { value: 'bank.example' } })
  fireEvent.click(screen.getByRole('button', { name: `${P}test.submit` }))
  fireEvent.click(await screen.findByRole('button', { name: `${P}test.open_policy No mail` }))
  const editor = await screen.findByRole('dialog', { name: `${P}editor.edit_title No mail` })
  fireEvent.click(within(editor).getByRole('button', { name: 'common:actions.cancel' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  fireEvent.click(screen.getByRole('tab', { name: `${P}lists.title` }))
  fireEvent.click(screen.getByRole('tab', { name: `${P}policies.title` }))
  await screen.findByRole('button', { name: `${P}policies.edit No mail` })
  expect(screen.queryByRole('dialog')).toBeNull()
})
it('shows filtered broad entries as a usable category, excluded from the problem filter', async () => {
  listsAPI([listSummary]); mount('/admin/access-control?tab=lists')
  const title = await screen.findAllByText('Finance'); expect(title.length).toBeGreaterThan(0)
  expect(screen.getAllByText(`${P}parse_report.broad_removed`).length).toBeGreaterThan(0)
  const tile = screen.getByRole('button', { name: `${P}lists.problem 0` })
  fireEvent.click(tile)
  await waitFor(() => expect(screen.queryByText('Finance')).toBeNull())
})
it('opens a bounded entry drawer and preserves the list tab when closing its cold link', async () => {
  listsAPI([listSummary]); const router = mount('/admin/access-control?tab=lists&sheet=list&list=7')
  const dialog = await screen.findByRole('dialog', { name: 'Finance' })
  expect(within(dialog).getByText('domain:bank.example')).toBeTruthy()
  expect(within(dialog).getByText('domain:hsbc')).toBeTruthy()
  fireEvent.change(within(dialog).getByRole('textbox', { name: `${P}list_entries.search` }), { target: { value: 'missing' } })
  expect(router.state.location.search).not.toContain('missing')
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists'))
})
it('opens the saved entries after list creation without a competing discard prompt', async () => {
  listsAPI([]); api.post.mockImplementation(async (url: string) => ({ data: url.endsWith('/preview') ? { parse_report: listReport, entries: ['domain:bank.example'], entry_count: 1, content_sha256: 'full-digest' } : { ...listDetail, kind: 'custom' } }))
  const router = mount('/admin/access-control?tab=lists')
  fireEvent.click(await screen.findByRole('button', { name: `${P}lists.create` }))
  fireEvent.change(await screen.findByRole('textbox', { name: `${P}list_editor.name` }), { target: { value: 'New list' } })
  fireEvent.change(screen.getByRole('textbox', { name: `${P}list_editor.text` }), { target: { value: 'bank.example' } })
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=lists&sheet=list&list=7'))
  expect(confirmation).not.toHaveBeenCalled()
})
it('distinguishes a first failed download from refresh failure retaining old content', async () => {
  listsAPI([{ ...listSummary, state: 'failed', last_fetched_at: null }, { ...listSummary, id: 8, name: 'Older list', state: 'failed', last_fetched_at: 1000 }]); mount('/admin/access-control?tab=lists')
  expect((await screen.findAllByText(`${P}lists.state_failed_first`)).length).toBeGreaterThan(0)
  expect(screen.getAllByText(`${P}lists.state_failed_old`).length).toBeGreaterThan(0)
})
it('keeps the entry drawer and its editor as distinct React children', async () => {
  const errors = vi.spyOn(console, 'error').mockImplementation(() => {})
  try {
    listsAPI([listSummary]); mount('/admin/access-control?tab=lists&sheet=list&list=7')
    const dialog = await screen.findByRole('dialog', { name: 'Finance' })
    fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.edit' }))
    await screen.findByRole('textbox', { name: `${P}list_editor.name` })
    expect(errors.mock.calls.some(args => args.some(value => String(value).includes('same key')))).toBe(false)
  } finally { errors.mockRestore() }
})
it('converts observation with every field, edit version and explicit risk choice without reading hit data', async () => {
  const observation = { ...samplePolicy, action: 'observe' as const, name: 'Watch', counts_as_risk: false, list_ids: [7], scope: 'groups' as const, group_ids: [3, 9], template_key: 'crypto', inline: { ports: '443', network: 'tcp' as const, cidrs: ['192.0.2.0/24'] } }
  let converted = false
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: converted ? [{ ...observation, action: 'block', counts_as_risk: true }] : [], observe: converted ? [] : [observation] }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } }))
  api.put.mockImplementation(async () => { converted = true; return { data: { ...observation, action: 'block', counts_as_risk: true, priority: 1, updated_at: 4000 } } })
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu Watch` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}promotion.action` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}promotion.title Watch` })
  fireEvent.click(within(dialog).getByRole('checkbox', { name: `${P}promotion.risk` }))
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}promotion.action` }))
  await waitFor(() => expect(api.put).toHaveBeenCalledWith('/admin/dest/policies/12', expect.objectContaining({ name: 'Watch', action: 'block', list_ids: [7], inline: observation.inline, scope: 'groups', group_ids: [3, 9], enabled: true, counts_as_risk: true, template_key: 'crypto', updated_at: 2000 }), { _skipErrorToast: true }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(api.get.mock.calls.some(([url]) => /\/(hits|records|usage)/.test(url))).toBe(false)
  expect(snack).toHaveBeenCalledWith(`${P}promotion.saved_position`, 'success')
})
it('keeps a stale conversion risk choice until explicit reload, and cancellation never updates the policy', async () => {
  let row = { ...samplePolicy, action: 'observe' as const, name: 'Watch', counts_as_risk: false }
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [], observe: [row] }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } }))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu Watch` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}promotion.action` }))
  let dialog = await screen.findByRole('dialog', { name: `${P}promotion.title Watch` })
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.cancel' }))
  expect(api.put).not.toHaveBeenCalled()
  fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu Watch` })); fireEvent.click(screen.getByRole('menuitem', { name: `${P}promotion.action` }))
  dialog = await screen.findByRole('dialog', { name: `${P}promotion.title Watch` })
  const risk = within(dialog).getByRole('checkbox', { name: `${P}promotion.risk` }) as HTMLInputElement
  fireEvent.click(risk); api.put.mockRejectedValueOnce(err(409, 'dest_policy_stale'))
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}promotion.action` }))
  const reload = await within(dialog).findByRole('button', { name: `${P}promotion.reload` })
  expect(risk.checked).toBe(true)
  row = { ...row, name: 'Latest', enabled: false, updated_at: 5000 }
  fireEvent.click(reload)
  await screen.findByRole('dialog', { name: `${P}promotion.title Latest` })
  expect(risk.checked).toBe(false)
  fireEvent.click(screen.getByRole('button', { name: `${P}promotion.action` }))
  await waitFor(() => expect(api.put).toHaveBeenLastCalledWith('/admin/dest/policies/12', expect.objectContaining({ name: 'Latest', enabled: false, counts_as_risk: false, updated_at: 5000 }), { _skipErrorToast: true }))
})
it('prevents duplicate promotion writes and closing while the save is pending', async () => {
  const row = { ...samplePolicy, action: 'observe' as const, name: 'Watch' }
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [], observe: [row] }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } }))
  let finish: (value: unknown) => void = () => {}
  api.put.mockImplementation(() => new Promise(resolve => { finish = resolve }))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu Watch` })); fireEvent.click(screen.getByRole('menuitem', { name: `${P}promotion.action` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}promotion.title Watch` })
  const submit = within(dialog).getByRole('button', { name: `${P}promotion.action` })
  fireEvent.click(submit); fireEvent.click(submit)
  await waitFor(() => expect(api.put).toHaveBeenCalledTimes(1))
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.cancel' }))
  expect(screen.getByRole('dialog')).toBe(dialog)
  finish({ data: { ...row, action: 'block' } })
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(snack).toHaveBeenCalledWith(`${P}promotion.saved`, 'success')
})
it('stops conversion when explicit reload finds a policy already changed to another action', async () => {
  let row = { ...samplePolicy, action: 'observe' as 'observe' | 'allow', name: 'Watch' }
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [], [row.action]: [row] }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } }))
  api.put.mockRejectedValueOnce(err(409, 'dest_policy_stale'))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu Watch` })); fireEvent.click(screen.getByRole('menuitem', { name: `${P}promotion.action` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}promotion.title Watch` })
  fireEvent.click(within(dialog).getByRole('button', { name: `${P}promotion.action` }))
  const reload = await within(dialog).findByRole('button', { name: `${P}promotion.reload` })
  row = { ...row, action: 'allow', updated_at: 5000 }; fireEvent.click(reload)
  await within(dialog).findByText(`${P}promotion.already_changed`)
  expect(within(dialog).queryByRole('button', { name: `${P}promotion.action` })).toBeNull()
  expect(api.put).toHaveBeenCalledTimes(1)
})
it('keeps risk selection when discard is declined and never writes on accepted cancellation', async () => {
  const row = { ...samplePolicy, action: 'observe' as const, name: 'Watch' }
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [], observe: [row] }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } }))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu Watch` })); fireEvent.click(screen.getByRole('menuitem', { name: `${P}promotion.action` }))
  const dialog = await screen.findByRole('dialog', { name: `${P}promotion.title Watch` })
  const risk = within(dialog).getByRole('checkbox', { name: `${P}promotion.risk` })
  fireEvent.click(risk); confirmation.mockResolvedValueOnce(false)
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.cancel' }))
  await waitFor(() => expect(confirmation).toHaveBeenCalledTimes(1))
  expect((risk as HTMLInputElement).checked).toBe(true)
  expect(screen.getByRole('dialog')).toBe(dialog)
  fireEvent.click(within(dialog).getByRole('button', { name: 'common:actions.cancel' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(api.put).not.toHaveBeenCalled()
})
it('opens a category template with actual cached counts and saves its list only with the policy', async () => {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [] }) : url.endsWith('/status') ? destinationStatus() : url.endsWith('/categories') ? { categories: [{ name: 'category-cryptocurrency', count: 37, regexp_count: 2, attrs: ['!cn'] }, { name: 'category-porn', count: 18, regexp_count: 11, attrs: [] }], updated_at: 1000 } : url.endsWith('/lists') || url.endsWith('/groups') ? { items: [], total: 0 } : { effective: {} } }))
  api.post.mockImplementation(async (url: string, input: Record<string, unknown>) => ({ data: url.endsWith('/preview') ? { budget: destinationBudget, new_list_preview: { parse_report: { accepted: 37, ignored: 1, ignored_broad: 1, rewritten: 0, samples: [{ line: 7, text: 'domain:hsbc', reason: 'broad_entry' }] }, entries: ['domain:exchange.test'], content_sha256: 'full-category-digest', entry_count: 37, regexp_count: 2, http_status: 0, bytes: 0 } } : { ...samplePolicy, ...input, id: 50, list_ids: [9] } }))
  mount()
  const use = await screen.findByRole('button', { name: `${P}templates.use ${P}policies.template_crypto` })
  expect(screen.getByText(`${P}templates.count 37/2`)).toBeTruthy()
  expect(screen.getByText(`${P}templates.count 18/11`)).toBeTruthy()
  expect(screen.queryByRole('heading', { name: `${P}policies.allow` })).toBeNull()
  fireEvent.click(use)
  expect((await screen.findByRole('textbox', { name: `${P}editor.name` }) as HTMLInputElement).value).toBe(`${P}policies.template_crypto`)
  await waitFor(() => expect(api.post.mock.calls.some(([url, input]) => url.endsWith('/policies/preview') && input.new_list?.geosite_category === 'category-cryptocurrency')).toBe(true))
  expect(api.post.mock.calls.some(([url]) => url.endsWith('/lists') || url.endsWith('/geosite/refresh'))).toBe(false)
  await screen.findByText(`${P}parse_report.broad_removed`)
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(api.post).toHaveBeenCalledWith('/admin/dest/policies', expect.objectContaining({ action: 'observe', enabled: true, counts_as_risk: false, template_key: 'crypto', list_ids: [], new_list: expect.objectContaining({ kind: 'geosite', geosite_category: 'category-cryptocurrency' }) }), { _skipErrorToast: true }))
})
it('shows missing-category download controls without automatically downloading or saving template lists', async () => {
  api.get.mockImplementation(async (url: string) => { if (url.endsWith('/categories')) throw err(503, 'dest_geosite_unavailable'); return { data: url.endsWith('/policies') ? destinationPolicies({ block: [] }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } } })
  mount()
  const downloads = await screen.findAllByRole('button', { name: `${P}categories.download` })
  expect(api.post).not.toHaveBeenCalled()
  fireEvent.click(downloads[0])
  await waitFor(() => expect(api.post).toHaveBeenCalledWith('/admin/dest/geosite/refresh', undefined, { _skipErrorToast: true }))
  expect(api.post.mock.calls.some(([url]) => url.endsWith('/lists') || url.endsWith('/policies'))).toBe(false)
})
it('opens templates from the new-policy menu even when policies already exist', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.create` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}policies.template_mail` }))
  expect((await screen.findByRole('textbox', { name: `${P}editor.ports` }) as HTMLInputElement).value).toBe('25,465,587')
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.cancel' }))
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
  expect(api.post.mock.calls.some(([url]) => url.endsWith('/lists') || url.endsWith('/policies'))).toBe(false)
})
it('opens list creation from the finance explanation without writing a policy or inventing a financial template', async () => {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [] }) : url.endsWith('/status') ? destinationStatus() : url.endsWith('/categories') ? { categories: [], updated_at: 1000 } : url.endsWith('/lists') ? { items: [], budget: destinationBudget, refresh_hours: 24 } : { effective: {} } }))
  const router = mount()
  fireEvent.click(await screen.findByRole('button', { name: `${P}templates.create_list` }))
  await screen.findByRole('textbox', { name: `${P}list_editor.name` })
  expect(router.state.location.search).toBe('?tab=lists')
  expect(api.post).not.toHaveBeenCalled()
})
it('keeps an over-quota category template editable but blocks saving its rejected preview', async () => {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: [], budget: { ...destinationBudget, regexps: { used: 250, limit: 256 } } }) : url.endsWith('/status') ? destinationStatus() : url.endsWith('/categories') ? { categories: [{ name: 'category-porn', count: 18, regexp_count: 11, attrs: [] }], updated_at: 1000 } : url.endsWith('/lists') || url.endsWith('/groups') ? { items: [], total: 0 } : { effective: {} } }))
  api.post.mockRejectedValue(err(400, 'dest_policy_over_limit'))
  mount()
  expect(await screen.findByRole('button', { name: `${P}templates.over_summary` })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: `${P}templates.use ${P}policies.template_porn` }))
  await screen.findByText(`${P}quota.exceeded`)
  expect((screen.getByRole('button', { name: 'common:actions.save' }) as HTMLButtonElement).disabled).toBe(true)
  expect(api.post.mock.calls.some(([url]) => url.endsWith('/policies') || url.endsWith('/lists'))).toBe(false)
})
it.each(['operator', 'user'] as const)('does not read access APIs for %s', async role => {
  useAuthStore.setState({ role }); mount()
  await screen.findByText('Dashboard')
  expect(api.get).not.toHaveBeenCalled()
})
it('toggles with every policy field and its version without treating the save as applied', async () => {
  mount(); const toggle = await screen.findByRole('switch', { name: `${P}policies.toggle No mail` })
  fireEvent.click(toggle)
  await waitFor(() => expect(api.put).toHaveBeenCalledWith('/admin/dest/policies/12', expect.objectContaining({ name: 'No mail', action: 'block', enabled: false, list_ids: [], inline: samplePolicy.inline, scope: 'all', group_ids: [], counts_as_risk: true, template_key: '', updated_at: 2000 }), { _skipErrorToast: true }))
  expect(confirmation).not.toHaveBeenCalled()
})
it('keeps a stale editor draft until the user explicitly loads the latest version', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const name = await screen.findByRole('textbox', { name: `${P}editor.name` })
  fireEvent.change(name, { target: { value: 'My draft' } })
  api.put.mockRejectedValueOnce(err(409, 'dest_policy_stale'))
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  const reload = await screen.findByRole('button', { name: `${P}editor.reload` })
  expect((name as HTMLInputElement).value).toBe('My draft')
  fireEvent.click(reload)
  await waitFor(() => expect((name as HTMLInputElement).value).toBe('No mail'))
})
it('requires first-enable confirmation using published facts and sends no write on cancellation', async () => {
  const disabled = { ...samplePolicy, enabled: false }
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ published_has_access_control: false, block: [disabled] }) : url.endsWith('/status') ? destinationStatus() : { effective: { dest_policy_apply_min_seconds: 75 } } }))
  confirmation.mockResolvedValue(false)
  mount(); fireEvent.click(await screen.findByRole('switch', { name: `${P}policies.toggle No mail` }))
  await waitFor(() => expect(confirmation).toHaveBeenCalledWith(expect.objectContaining({ title: `${P}confirm.first_title` })))
  expect(api.put).not.toHaveBeenCalled()
})
it('does not render policy controls when the destination service is unavailable', async () => {
  api.get.mockRejectedValue(err(503, 'dest_unwired')); mount()
  await screen.findByText(`${P}unwired`)
  expect(screen.queryByRole('switch')).toBeNull()
})
it('opens node coverage from an owned URL and closes it with Back', async () => {
  const router = mount()
  fireEvent.click(await screen.findByRole('button', { name: `${P}coverage.open` }))
  const drawer = await screen.findByRole('dialog', { name: `${P}coverage.title` })
  expect(router.state.location.search).toContain('sheet=nodes')
  fireEvent.click(within(drawer).getByRole('button', { name: new RegExp(`${P}coverage.filter_applied`) }))
  expect(router.state.location.search).toContain('node_state=applied')
  expect(router.state.location.state).toMatchObject({ drawer: 'sheet' })
  fireEvent.click(within(drawer).getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe(''))
})
it('removes owned node filters when closing a cold coverage deep link without changing the tab', async () => {
  const router = mount('/admin/access-control?tab=policies&sheet=nodes&node_state=problem')
  const drawer = await screen.findByRole('dialog', { name: `${P}coverage.title` })
  fireEvent.click(within(drawer).getByRole('button', { name: 'common:actions.close' }))
  await waitFor(() => expect(router.state.location.search).toBe('?tab=policies'))
})
it('submits every ID in the action segment when moving, including disabled policies', async () => {
  const rows = [samplePolicy, { ...samplePolicy, id: 19, name: 'Disabled', enabled: false }]
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies({ block: rows }) : url.endsWith('/status') ? destinationStatus() : { effective: {} } }))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu No mail` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}policies.down` }))
  await waitFor(() => expect(api.put).toHaveBeenCalledWith('/admin/dest/policies/order', { action: 'block', ids: [19,12] }, { _skipErrorToast: true }))
})
it('requires destructive confirmation for deletion and sends no delete on cancellation', async () => {
  confirmation.mockResolvedValue(false)
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.menu No mail` }))
  fireEvent.click(screen.getByRole('menuitem', { name: 'common:actions.delete' }))
  await waitFor(() => expect(confirmation).toHaveBeenCalledWith(expect.objectContaining({ destructive: true })))
  expect(api.delete).not.toHaveBeenCalled()
})
it('blocks saving a preview that exceeds the server budget', async () => {
  api.post.mockResolvedValue({ data: { budget: { ...destinationPolicies().budget, domains: { used: 50001, limit: 50000 } } } })
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const name = await screen.findByRole('textbox', { name: `${P}editor.name` })
  fireEvent.change(name, { target: { value: 'New name' } })
  await waitFor(() => expect((screen.getByRole('button', { name: 'common:actions.save' }) as HTMLButtonElement).disabled).toBe(true))
  await screen.findByText(`${P}quota.exceeded`)
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  expect(api.put).not.toHaveBeenCalled()
})
it('keeps save available after a preview read fails and still validates at the write endpoint', async () => {
  api.post.mockRejectedValue(err(500, 'preview_read_failed'))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const name = await screen.findByRole('textbox', { name: `${P}editor.name` })
  fireEvent.change(name, { target: { value: 'New name' } })
  await screen.findByText(`${P}editor.preview_failed`)
  expect((screen.getByRole('button', { name: 'common:actions.save' }) as HTMLButtonElement).disabled).toBe(false)
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(api.put).toHaveBeenCalled())
})
it('keeps a duplicate-name draft and attaches the error to its name field', async () => {
  api.put.mockRejectedValue(err(409, 'dest_name_taken'))
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const name = await screen.findByRole('textbox', { name: `${P}editor.name` })
  fireEvent.change(name, { target: { value: 'Taken' } })
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(name.getAttribute('aria-invalid')).toBe('true'))
  expect((name as HTMLInputElement).value).toBe('Taken')
})
it('does not announce the publication countdown through the primary live region', async () => {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus({ generation: 2, next_publish_at: Date.now() + 10000 }) : { effective: {} } }))
  mount(); const live = await screen.findByRole('status')
  await waitFor(() => expect(live.textContent).toBe(`${P}verdict.unpublished`))
  expect(live.textContent).not.toContain('countdown')
  expect(screen.getByLabelText(`${P}publish_at`)).toBeTruthy()
})
it('does not claim fallback exhaustion is applied until the empty candidate is confirmed', async () => {
  api.get.mockImplementation(async (url: string) => ({ data: url.endsWith('/policies') ? destinationPolicies() : url.endsWith('/status') ? destinationStatus({ nodes: [destinationNode({ fallback_exhausted: true, minted_kind: 'empty', pending_since: 3000, applied_at: 2000, minted_at: 3000 })] }) : { effective: {} } }))
  mount('/admin/access-control?sheet=nodes')
  await screen.findByText(`${P}coverage.fallback_stopping`)
  expect(screen.queryByText(`${P}coverage.fallback_exhausted`)).toBeNull()
})
it('reports saved pause state after a failed publication instead of claiming the fleet is paused', async () => {
  api.put.mockRejectedValue({ isAxiosError: true, response: { status: 503, data: { error: 'dest_policy_publish_unavailable', pause_saved: true, paused: true } } })
  mount(); await screen.findByRole('status'); fireEvent.click(screen.getByRole('button', { name: `${P}more` })); fireEvent.click(screen.getByRole('menuitem', { name: `${P}pause` }))
  await waitFor(() => expect(snack).toHaveBeenCalledWith(`${P}pause_saved`, 'error'))
  expect(api.put).toHaveBeenCalledWith('/admin/dest/pause', { paused: true }, { _skipErrorToast: true })
})
it('blocks navigation that would discard an editor draft when the user cancels', async () => {
  confirmation.mockResolvedValue(false)
  const router = mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.edit No mail` }))
  const name = await screen.findByRole('textbox', { name: `${P}editor.name` })
  fireEvent.change(name, { target: { value: 'Unsaved' } })
  await router.navigate('/admin/dashboard')
  await waitFor(() => expect(confirmation).toHaveBeenCalledWith(expect.objectContaining({ title: `${P}confirm.discard_title` })))
  expect(router.state.location.pathname).toBe('/admin/access-control')
  expect((name as HTMLInputElement).value).toBe('Unsaved')
})
it('creates a disabled policy with a full create body and no existing version fields', async () => {
  mount(); fireEvent.click(await screen.findByRole('button', { name: `${P}policies.create` }))
  fireEvent.click(screen.getByRole('menuitem', { name: `${P}templates.blank` }))
  fireEvent.change(await screen.findByRole('textbox', { name: `${P}editor.name` }), { target: { value: 'New policy' } })
  fireEvent.click(screen.getByRole('button', { name: `${P}editor.more_conditions` }))
  fireEvent.change(screen.getByRole('textbox', { name: `${P}editor.ports` }), { target: { value: '443' } })
  fireEvent.click(screen.getByRole('button', { name: 'common:actions.save' }))
  await waitFor(() => expect(api.post).toHaveBeenCalledWith('/admin/dest/policies', expect.objectContaining({ name: 'New policy', action: 'block', enabled: false, inline: expect.objectContaining({ ports: '443' }), list_ids: [], scope: 'all', group_ids: [] }), { _skipErrorToast: true }))
  const body = api.post.mock.calls.find(call => call[0] === '/admin/dest/policies')![1]
  expect(body).not.toHaveProperty('updated_at'); expect(body).not.toHaveProperty('id')
})
